/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadejemplo.Vistas;

import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import universidadejemplo.AccesoADatos.AlumnoData;
import universidadejemplo.Entidades.Alumno;


/**
 *
 * @author Faris
 */
public class ManejoDeInscripcionesView extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo = new DefaultTableModel(new Object[]{"ID Alumno", "DNI", "Apellido", "Nombre"}, 0);
    /**
     * Creates new form InscripcionesView
     */
    public ManejoDeInscripcionesView() {
       
               
        initComponents();
        llenarComboBox();
        armarCabeceras();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JCBalumno = new javax.swing.JComboBox<>();
        JRBmateriasincriptas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTtabla = new javax.swing.JTable();
        JBinscribir = new javax.swing.JButton();
        JBanular = new javax.swing.JButton();
        JBsalir = new javax.swing.JButton();
        JRBmateriasnoinscriptas = new javax.swing.JRadioButton();

        setTitle("Formulario de Inscripcion");

        jLabel2.setText("Seleccione un Alumno");

        jLabel3.setText("Listado de materias");

        JCBalumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JCBalumno.setToolTipText("Seleccione un Alumno de la lista");
        JCBalumno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JCBalumnoItemStateChanged(evt);
            }
        });
        JCBalumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBalumnoActionPerformed(evt);
            }
        });

        JRBmateriasincriptas.setText("Materias Inscriptas");

        JTtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTtabla);

        JBinscribir.setText("Inscribir");

        JBanular.setText("Anular Inscripcion");

        JBsalir.setText("Salir");

        JRBmateriasnoinscriptas.setText("Materias no Inscriptas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(JCBalumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JRBmateriasincriptas)
                                .addGap(53, 53, 53)
                                .addComponent(JRBmateriasnoinscriptas))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(JBinscribir)
                                .addGap(84, 84, 84)
                                .addComponent(JBanular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JBsalir))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JCBalumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JRBmateriasincriptas)
                    .addComponent(JRBmateriasnoinscriptas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBinscribir)
                    .addComponent(JBanular)
                    .addComponent(JBsalir))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCBalumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBalumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBalumnoActionPerformed

    private void JCBalumnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCBalumnoItemStateChanged
        // TODO add your handling code here:
        //este if lo que hace es agregar en la tabla el objeto seleccionado dentro de el combo box
        if(evt.getStateChange() == ItemEvent.SELECTED){
            String objetoEnJCB = (String) JCBalumno.getSelectedItem();
            
           
        }
    }//GEN-LAST:event_JCBalumnoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBanular;
    private javax.swing.JButton JBinscribir;
    private javax.swing.JButton JBsalir;
    private javax.swing.JComboBox<String> JCBalumno;
    private javax.swing.JRadioButton JRBmateriasincriptas;
    private javax.swing.JRadioButton JRBmateriasnoinscriptas;
    private javax.swing.JTable JTtabla;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    
    private void  llenarComboBox(){
        AlumnoData alumd = new AlumnoData();
        List<Alumno> listaAlumnos = alumd.listarAlumnos();
       
        JCBalumno.removeAllItems();
        
        for (int i = 0 ; i < listaAlumnos.size(); i++){
        JCBalumno.addItem(String.valueOf(listaAlumnos.get(i).getDni())+ ", "+ listaAlumnos.get(i).getApellido()+", "+listaAlumnos.get(i).getNombre()) ;
    }
    }

    private void armarCabeceras(){
   // modelo.addColumn("ID Materia");
   // modelo.addColumn("Nombre");
    //modelo.addColumn("Año");
    JTtabla.setModel(modelo);
    } 
    

}
